from __future__ import annotations

import struct
import sys
from pathlib import Path


MARKERS = (
    bytes.fromhex("48 B8 4C 45 48 53 4C 49 41 59 C3"),
    bytes.fromhex("B8 4C 45 48 53 BA 4C 49 41 59 C3"),
)


def read_yail_section(image: bytes) -> bytes:
    pe_offset = struct.unpack_from("<I", image, 0x3C)[0]
    if image[:2] != b"MZ" or image[pe_offset : pe_offset + 4] != b"PE\0\0":
        raise ValueError("input is not a PE image")

    section_count = struct.unpack_from("<H", image, pe_offset + 6)[0]
    optional_header_size = struct.unpack_from("<H", image, pe_offset + 20)[0]
    section_offset = pe_offset + 24 + optional_header_size
    for index in range(section_count):
        offset = section_offset + index * 40
        name = image[offset : offset + 8].rstrip(b"\0")
        if name != b".yail":
            continue

        raw_size, raw_offset = struct.unpack_from("<II", image, offset + 16)
        return image[raw_offset : raw_offset + raw_size]

    raise ValueError("input PE does not contain a .yail section")


def read_shellcode(path: Path) -> bytes:
    section = read_yail_section(path.read_bytes())
    for marker in MARKERS:
        marker_offset = section.find(marker)
        if marker_offset >= 0:
            return section[:marker_offset]
    raise ValueError(f"{path}: .yail shellcode end marker was not found")


def format_array(name: str, shellcode: bytes) -> str:
    values = [f"0x{byte:02X}" for byte in shellcode]
    lines = [", ".join(values[index : index + 16]) for index in range(0, len(values), 16)]
    body = ",\n        ".join(lines)
    return f"""    inline constexpr std::array<std::uint8_t, {len(shellcode)}> {name}{{
        {body}
    }};"""


def format_header(x64_shellcode: bytes, x86_shellcode: bytes) -> str:
    return f"""// Generated by tools/generate_shellcode.py. Do not edit manually.
#pragma once
#include <array>
#include <cstdint>

namespace yail::detail
{{
{format_array("x64_remote_shellcode", x64_shellcode)}

{format_array("x86_remote_shellcode", x86_shellcode)}
}}
"""


def main() -> None:
    if len(sys.argv) != 4:
        raise SystemExit("usage: generate_shellcode.py <x64-yail-pe> <x86-yail-pe> <output-header>")

    x64_source = Path(sys.argv[1])
    x86_source = Path(sys.argv[2])
    output = Path(sys.argv[3])
    output.write_text(format_header(read_shellcode(x64_source), read_shellcode(x86_source)), encoding="ascii")


if __name__ == "__main__":
    main()
